AWSTemplateFormatVersion: "2010-09-09"
Description: Full serverless image upload app with static website, Lambda, API Gateway, S3 uploads, CloudFront and Route53

Parameters:
  WebBucketName:
    Type: String
    Default: image-upload-web-498747779442
    Description: Bucket for static website files

  UploadBucketName:
    Type: String
    Default: celebrity-upload-498747779442
    Description: Bucket for uploaded images (private)

  DomainName:
    Type: String
    Description: Your custom domain (e.g. upload.midominio.com)

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for your domain

Resources:

# ==================================================
# S3 Web Bucket
# ==================================================
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# ==================================================
# CloudFront Distribution
# ==================================================
  WebCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  WebDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: WebOrigin
            DomainName: !GetAtt WebBucket.RegionalDomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: WebOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref WebCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

# ==================================================
# Route53 Record
# ==================================================
  WebsiteDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront fixed HostedZoneId

# ==================================================
# S3 Uploads Bucket
# ==================================================
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# ==================================================
# IAM Role for Lambda
# ==================================================
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-upload-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: upload-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:aws:s3:::${UploadBucketName}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

# ==================================================
# Lambda Function
# ==================================================
  UploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: generate-upload-url
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref UploadBucketName
      Code:
        ZipFile: |
          import json, boto3, os, time
          s3 = boto3.client("s3")
          BUCKET = os.environ["BUCKET_NAME"]
          ALLOWED = ["image/png","image/jpeg","image/gif","image/webp"]

          def lambda_handler(event, context):
              body = json.loads(event.get("body","{}"))
              if "filename" not in body or "contentType" not in body:
                  return resp(400,"Missing filename or contentType")
              if body["contentType"] not in ALLOWED:
                  return resp(400,"Invalid type")
              key = f"uploads/{int(time.time())}-{body['filename']}"
              url = s3.generate_presigned_url(
                  "put_object",
                  Params={"Bucket":BUCKET,"Key":key,"ContentType":body["contentType"]},
                  ExpiresIn=60
              )
              return {"statusCode":200,"headers":{"Access-Control-Allow-Origin":"*"},"body":json.dumps({"uploadUrl":url})}

          def resp(c,m):
              return {"statusCode":c,"headers":{"Access-Control-Allow-Origin":"*"},"body":json.dumps({"error":m})}

# ==================================================
# API Gateway
# ==================================================
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: upload-api
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["POST","OPTIONS"]
        AllowHeaders: ["*"]

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt UploadLambda.Arn
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /upload-url"
      Target: !Sub integrations/${Integration}

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: "$default"
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UploadLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub ${HttpApi.ExecutionArn}/*/*

# ==================================================
# Outputs
# ==================================================
Outputs:
  WebsiteURL:
    Description: URL of the static website via CloudFront
    Value: !Sub https://${DomainName}

  UploadApiUrl:
    Description: API endpoint for uploading images
    Value: !Sub ${HttpApi.ApiEndpoint}/upload-url
