AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  UserEmail:
    Type: String
    Default: 'manugalang2007@gmail.com'

Resources:
  # 1. THE WEBSITE HOSTING (S3)
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false

  # 2. THE PERMISSION FIX (Explicitly naming the role from your error)
  WebsiteBucketPipelinePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              # We use the IAM Role ARN that corresponds to your assumed-role error
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-us-east-1-Celebrity-Detector-Sync"
            Action: 
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetBucketLocation
              - s3:ListBucket
            Resource: 
              - !Sub "arn:aws:s3:::${WebsiteBucket}"
              - !Sub "arn:aws:s3:::${WebsiteBucket}/*"
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  # 3. THE IMAGE UPLOAD BUCKET
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "celebrity-upload-${AWS::AccountId}-v2"
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ImageProcessQueue.Arn
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [PUT, POST]
            AllowedOrigins: ['*']

  # 4. DYNAMODB TABLE
  CelebrityResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageKey
          AttributeType: S
      KeySchema:
        - AttributeName: ImageKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 5. SNS NOTIFICATION
  CelebrityAlertTopic:
    Type: AWS::SNS::Topic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref CelebrityAlertTopic
      Protocol: email
      Endpoint: !Ref UserEmail

  # 6. LAMBDA EXECUTION ROLE (Permissions for the Python Logic)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CelebrityProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:RecognizeCelebrities
                  - s3:GetObject
                  - dynamodb:PutItem
                  - sns:Publish
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "*"

  # 7. PROCESSING LAMBDA
  ProcessingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref CelebrityResultsTable
          SNS_TOPIC_ARN: !Ref CelebrityAlertTopic
      Code:
        ZipFile: |
          import boto3, os, json, urllib.parse
          rek = boto3.client('rekognition')
          ddb = boto3.resource('dynamodb').Table(os.environ['TABLE_NAME'])
          sns = boto3.client('sns')
          def handler(event, context):
              for record in event['Records']:
                  s3_event = json.loads(record['body'])
                  if 'Records' not in s3_event: continue
                  for s3_rec in s3_event['Records']:
                      b = s3_rec['s3']['bucket']['name']
                      k = urllib.parse.unquote_plus(s3_rec['s3']['object']['key'])
                      res = rek.recognize_celebrities(Image={'S3Object':{'Bucket':b,'Name':k}})
                      name = res['CelebrityFaces'][0]['Name'] if res['CelebrityFaces'] else "Unknown"
                      ddb.put_item(Item={'ImageKey': k, 'CelebrityName': name})
                      sns.publish(TopicArn=os.environ['SNS_TOPIC_ARN'], 
                                  Message=f"Detected: {name} in {k}", 
                                  Subject="Celebrity Alert!")
              return {"status":"ok"}

  # 8. SQS QUEUE & LAMBDA TRIGGER
  ImageProcessQueue:
    Type: AWS::SQS::Queue

  LambdaSQSEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt ImageProcessQueue.Arn
      FunctionName: !Ref ProcessingLambda

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref ImageProcessQueue]
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: {Service: s3.amazonaws.com}
            Action: sqs:SendMessage
            Resource: !GetAtt ImageProcessQueue.Arn

  # 9. GUEST PASS (Cognito Identity Pool)
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true

  IdentityPoolRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
      Policies:
        - PolicyName: GuestUploadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::celebrity-upload-${AWS::AccountId}-v2/*"

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        unauthenticated: !GetAtt IdentityPoolRole.Arn

Outputs:
  MyIdentityPoolId:
    Description: "Copy this into your index.html"
    Value: !Ref IdentityPool
  WebsiteURL:
    Description: "Your Live Website Link"
    Value: !GetAtt WebsiteBucket.WebsiteURL